"""Pool Sauce — shot intelligence for The Way of the Pool Player."""
from poolsauce.constants import (
    BALL_BALL_RESTITUTION,
    BALL_MASS_KG,
    BALL_RADIUS_M,
    CLOTH_ROLLING_FRICTION,
    CLOTH_SLIDING_FRICTION,
    CLOTH_SPINNING_FRICTION,
    CUSHION_EFFICIENCY,
    TABLE_9FT_LENGTH_M,
    TABLE_9FT_WIDTH_M,
)
from poolsauce.composer import (
    Intention,
    SauceChoice,
    compose_pillar_plan,
)
from poolsauce.debrief import (
    DebriefOverrides,
    compose_debrief,
)
from poolsauce.physics import (
    GRAVITY_M_S2,
    RAIL_OUTWARD_NORMALS,
    SimEvent,
    SimulationResult,
    advance_to_rest,
    ball_collision,
    contact_slip,
    cushion_rebound,
    is_rolling,
    simulate,
    step_free_flight,
)
from poolsauce.schema import (
    DEFAULT_SCHEMA_PATH,
    load_pillar_schema,
    validate_pillar_output,
)
from poolsauce.sauce import (
    SAUCE_ENGLISH,
    SAUCE_STROKE,
    TIP_FRACTION_OF_R,
    SaucePrescription,
    angular_velocity_to_tip_offsets,
    cue_state_from_sauce,
    describe_stroke,
    stroke_to_cue_state,
    tip_offsets_from_phrases,
)
from poolsauce.solver import (
    CueDestinationRecipe,
    ShotPlan,
    ShotSolverError,
    cue_state_for_plan,
    cue_state_from_recipe,
    solve_cue_destination,
    solve_direct_shot,
)
from poolsauce.state import POCKET_NAMES, Ball, Table, TableState
from poolsauce.zones import (
    ZoneClassification,
    classify_zone_by_distance,
    classify_zone_for_next_shot,
)

__all__ = [
    "Ball",
    "Table",
    "TableState",
    "POCKET_NAMES",
    "BALL_RADIUS_M",
    "BALL_MASS_KG",
    "TABLE_9FT_LENGTH_M",
    "TABLE_9FT_WIDTH_M",
    "CLOTH_SLIDING_FRICTION",
    "CLOTH_ROLLING_FRICTION",
    "CLOTH_SPINNING_FRICTION",
    "CUSHION_EFFICIENCY",
    "BALL_BALL_RESTITUTION",
    "DEFAULT_SCHEMA_PATH",
    "load_pillar_schema",
    "validate_pillar_output",
    "GRAVITY_M_S2",
    "RAIL_OUTWARD_NORMALS",
    "contact_slip",
    "is_rolling",
    "step_free_flight",
    "advance_to_rest",
    "cushion_rebound",
    "ball_collision",
    "SimEvent",
    "SimulationResult",
    "simulate",
    "ShotPlan",
    "ShotSolverError",
    "CueDestinationRecipe",
    "solve_direct_shot",
    "solve_cue_destination",
    "cue_state_for_plan",
    "cue_state_from_recipe",
    "SAUCE_ENGLISH",
    "SAUCE_STROKE",
    "TIP_FRACTION_OF_R",
    "SaucePrescription",
    "angular_velocity_to_tip_offsets",
    "cue_state_from_sauce",
    "describe_stroke",
    "stroke_to_cue_state",
    "tip_offsets_from_phrases",
    "ZoneClassification",
    "classify_zone_by_distance",
    "classify_zone_for_next_shot",
    "Intention",
    "SauceChoice",
    "compose_pillar_plan",
    "DebriefOverrides",
    "compose_debrief",
]
